version: '3.1'

services:

    openkm:
        build: .
        volumes:
            - ./okmrepo:/mnt/okmrepo
        ports:
            - 8080:8080
            - 2002:2002
        depends_on:
            - openkm_db
    openkm_db:
        image: mysql:5.7
        restart: always
        volumes:
            - ./data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=!QAZ2wsx#EDC
            - MYSQL_DATABASE=okmdb
        ports:
            - 3306:3306

